### PR TITLE
Fix psi module dependency

### PR DESCRIPTION
**Pull request by egorikftp**
Fixes https://github.com/ComposeGears/Valkyrie/pull/108#discussion_r1712611618.

### CODE REVIEW

**Comment by egorikftp** [comment]
I think should be as `pluginModule`

https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-plugins.html#module

**Comment by Goooler** [comment]
It works https://github.com/ComposeGears/Valkyrie/actions/runs/10330644000/job/28599926138.

**Comment by egorikftp** [comment]
Ok, let's process as regular dependency

**Review by Goooler — APPROVED** [review]
All we have to do is make sure psi module jar has been included in the final distribution, `bundledPlugin` is just for getting rid of bundling `kotlin-compiler-embeddable`.

**Pull request merged**
