### PR TITLE
Preview functions should start with Preview

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by egorikftp** [comment]
@Goooler why preview keyword should be at the beginning?
Didn't f saw any official guidelines, but Google follow this name convention: https://developer.android.com/develop/ui/compose/tooling/previews

**Comment by Goooler** [comment]
This was ever introduced in https://mrmans0n.github.io/compose-rules/rules/, maybe, but removed now.

Closing now, it's not much necessary.

**Comment by egorikftp** [comment]
It was my feature request 😀 

https://github.com/mrmans0n/compose-rules/issues/229

**Comment by Goooler** [comment]
Good to know.

**Pull request closed without merging**
