### PR TITLE
Exclude kotlin-compiler-embeddable in distributions

### PR DESCRIPTION
**Pull request by Goooler**
```
 117.96 MB valkyrie-0.6.0-SNAPSHOT-after.zip
 184.73 MB valkyrie-0.6.0-SNAPSHOT-before.zip
```

### CODE REVIEW

**Comment by Goooler** [comment]
Please check the related feature in #67.

**Comment by egorikftp** [comment]
oh, nice catch!

**Comment by egorikftp** [comment]
waiting compose multiplatform embedded 😄

**Comment by Goooler** [comment]
Do you mean we can exclude compose-desktop deps as well?

**Comment by egorikftp** [comment]
> Do you mean we can exclude compose-desktop deps as well?

they have this one, but last time I tried it not worked

https://github.com/JetBrains/compose-multiplatform/blob/master/tooling/compose-intellij-platform/README.md

**Comment by egorikftp** [comment]
> It's about 75 MB now.
> 
> These libs are excluded now, we have to make sure this plugin can work on Windows or Linux.
> 
> ```
>    8.94 MB skiko-awt-runtime-macos-x64-0.8.4.jar
>   10.35 MB skiko-awt-runtime-linux-arm64-0.8.4.jar
>   10.53 MB skiko-awt-runtime-windows-x64-0.8.4.jar
>   12.35 MB skiko-awt-runtime-linux-x64-0.8.4.jar
> ```

Looks like will not work without
telegram-cloud-photo-size-2-5305322013121961851-y

**Comment by Goooler** [comment]
Yeah, I've confirmed they are still necessary on Linux devices.

**Comment by egorikftp** [comment]
We can leave it as it is for now and wait for more news from JetBrains. The mentioned plugin hasn't been updated for 2 years, and it's dangerous to use in production 🙂

**Comment by Goooler** [comment]
Reverted, I'll squash this PR later.

**Comment by Goooler** [comment]
Can you verify #67 after this excluding? I'm not very sure if we can drop kotlin-compiler-embeddable.

**Comment by egorikftp** [comment]
It's crash 🙁 

```kotlin
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/com/intellij/openapi/project/Project
	at io.github.composegears.valkyrie.psi.ProjectKt.<clinit>(Project.kt:8)
	at io.github.composegears.valkyrie.psi.IconPackPsiParser.extractIconPack(IconPackPsiParser.kt:23)

```

**Comment by Goooler** [comment]
Alright, we still need it.

**Pull request closed without merging**
