### PR TITLE
Build CLI distribution zip

### PR DESCRIPTION
**Pull request by egorikftp**
@Goooler On top of your logic I added this [logic](https://ajalt.github.io/clikt/quickstart/#developing-command-line-applications-with-gradle) to avoid `java -jar` call

Final zip located in `distributions` folder

Screenshot 2024-11-18 at 21 23 06

### CODE REVIEW

**Comment by Goooler** [comment]
`binaryJar` already makes this jar executable.

**Comment by egorikftp** [comment]
> `binaryJar` already makes this jar executable.

For me it's not working. Only with 'java -jar'.
Also tried on your cli tool, the same behavior

**Comment by Goooler** [comment]
May have to mark it executable. `chmod +x ...`

**Comment by Goooler** [comment]
I'm fine with migrating to `installDist`, in that case there is no need to build a fat jar or r8 jar, just align with https://github.com/JakeWharton/diffuse did.

**Comment by egorikftp** [comment]
I don't know what's better. 
With shadow jar all `jar`s from `libs` folder merged into single one and then with r8 I decrease size from 43mb to 8mb

**Comment by egorikftp** [comment]
@Goooler two options:

shadow + r8 = 8.5mb
Screenshot 2024-11-19 at 12 17 43

pure `installDist` = 47.2mb
Screenshot 2024-11-19 at 12 18 48

**Comment by vkatz** [comment]
8mb looks better... and will be better for some cli tools (so you can locate jar and use it in pipeline takin less space)

**Pull request merged**
